### ISSUE TITLE
subscribe to program updates

### ISSUE THREAD

**Issue by shardyr** [weeaa/jito-go#1]
Hey, is it possible to subscribe to program updates? If not, when is this feature going to be added?

**Comment by weeaa** [comment]
Hi there, if you're referring to [this function](https://github.com/weeaa/jito-go/blob/main/clients/geyser_client/geyser.go#L122), then yes it _should_ be possible. You would need a Geyser compatible RPC since Jito discontinued their own afaik.

I'm unable to test (since I do not own a compatible node) but will happily test if you own one 😊

**Comment by weeaa** [comment]
Heyo, added the function to subscribe to programs. I also added bundle simulation, you would require a compatible jito-solana validator to perform the request.

thanks, appreciate your message and support ❤️
